name: Docker Action
inputs: 
  who_to_greet:
    description: 'Who To Greet'
    required: True
    default: 'world'
outputs:
  time:
    description: "we said hello at this time..."
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who_to_greet }}
