name: Build with Docker Container
on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run my action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who_to_greet: 'alex'
      - name: Output time
        run: echo "Time was ${{ steps.hello-action.outputs.time }} when it said hello. "
